### ISSUE TITLE
android link from download page behaves weirdly

### ISSUE THREAD

**Issue by mpguerra** [torproject/tpo#14]
https://trac.torproject.org/projects/tor/ticket/29473

**Comment by mpguerra** [comment]
We should remove that redirect action on the android link and put it at the call to actions we have at the button

**Comment by hiromipaw** [comment]
I think this is fixed.

**Comment by holantonela** [comment]
and, the anchor link fixed at commit ecd0ca28f295032ba2375988fcd3bd418beb44f7
